repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    sha: v0.5.0
    hooks:
      - id: markdownlint

  - repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
      - id: shell-lint

  - repo: git://github.com/kintoandar/pre-commit.git
    sha: v2.1.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: node_modules/.bin/prettier --write
        language: node
        files: \.(js|jsx)$

  -   repo: git://github.com/dnephin/pre-commit-golang
      sha: 823c25f40e37d52765b6469de6df94c08e678784
      hooks:
      -   id: go-fmt
      -   id: go-vet
      -   id: go-lint
